=== sheartnet13/Lnd-Schema/mission_log_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com"
    xmlns="https://www.w3schools.com" elementFormDefault="qualified">

    <xs:element name="MissionLog" type="MissionLogType"/>

    <xs:complexType name="MissionLogType">
        <xs:sequence>
            <xs:element name="Player" type="xs:string"/>
            <xs:element name="MissionType" type="xs:string"/>
            <xs:element name="Date" type="xs:dateTime"/>
            <xs:element name="Location" type="xs:string"/>
            <xs:element name="Description" type="xs:string" minOccurs="0"/>
            <xs:element name="Crew" type="CrewType" minOccurs="1"/>
            <xs:element name="Resources" type="ResourcesType"/>
        </xs:sequence>
    </xs:complexType>

        <xs:complexType name="CrewType">
        <xs:sequence>
            <xs:element name="Member" type="xs:string" minOccurs="1" maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResourcesType">
        <xs:sequence>
            <xs:element name="Resource" type="ResourceType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResourceType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Amount" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="unit" type="xs:string" use="optional"/>
    </xs:complexType>

</xs:schema>

=== sheartnet13/Lnd-Schema/mission_log1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MissionLog xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com mission_log_schema.xsd">
    <Player>StarPilot42</Player>
    <MissionType>Exploration</MissionType>
    <Date>2026-01-19T14:30:00</Date>
    <Location>ArcCorp</Location>
    <Description>Exploring ArcCorp for new mining locations.</Description>
    <Crew>
        <Member>StarPilot42</Member>
        <Member>CoPilotX</Member>
    </Crew>
    <Resources>
        <Resource unit="kg">
            <Name>Quantanium</Name>
            <Amount>50</Amount>
        </Resource>
        <Resource unit="kg">
            <Name>Gold</Name>
            <Amount>20</Amount>
        </Resource>
    </Resources>
</MissionLog>

=== sheartnet13/Lnd-Schema/mission_log2.xml
<?xml version="1.0" encoding="UTF-8"?>
<MissionLog xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com mission_log_schema.xsd">
    <Player>NovaTrader</Player>
    <MissionType>Trade</MissionType>
    <Date>2026-01-20T09:15:00</Date>
    <Location>Hurston</Location>
    <Crew>
        <Member>NovaTrader</Member>
        <Member>TradeBot</Member>
        <Member>SecurityGuy</Member>
    </Crew>
    <Resources>
        <Resource unit="kg">
            <Name>Laranite</Name>
            <Amount>10</Amount>
        </Resource>
        <Resource unit="ct">
            <Name>Diamond</Name>
            <Amount>5</Amount>
        </Resource>
    </Resources>
</MissionLog>
